# Generated by Django 5.0.3 on 2024-05-25 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='taxprice',
            new_name='taxPrice',
        ),
    ]
