# Generated by Django 5.0.3 on 2024-05-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='isDelivered',
            field=models.BooleanField(default=False),
        ),
    ]
