# Generated by Django 5.0.3 on 2024-07-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_order_isdelivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/dummy.png', null=True, upload_to=''),
        ),
    ]
